# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-24 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=200, upload_to='img', verbose_name='\u56fe\u7247')),
                ('url', models.URLField(max_length=500, verbose_name='\u5546\u54c1\u94fe\u63a5')),
                ('desc', models.TextField(verbose_name='\u56fe\u7247\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fe\u7247\u5e93',
                'verbose_name_plural': '\u56fe\u7247\u5e93',
            },
        ),
    ]
