# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-24 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Queryimg', verbose_name='\u56fe\u7247')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='\u7528\u6237ip')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u67e5\u8be2\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u67e5\u8be2\u5386\u53f2',
                'verbose_name_plural': '\u67e5\u8be2\u5386\u53f2',
            },
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='\u56fe\u7247'),
        ),
    ]
