# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_auto_20181024_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='action ip'),
        ),
    ]
