# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0010_auto_20181025_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='img',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='CLSMats', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='img',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='upload', verbose_name='\u56fe\u7247'),
        ),
    ]
