# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0011_auto_20181026_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryhistory',
            name='img',
            field=models.ImageField(upload_to='upload', verbose_name='\u56fe\u7247'),
        ),
    ]
